// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAgaEMCFXOK7u5EIiUjJ9_CRdjCqbiBtI',
    appId: '1:716646968054:web:03b6a2e49d411bb97e9ad7',
    messagingSenderId: '716646968054',
    projectId: 'todoapp-f05fe',
    authDomain: 'todoapp-f05fe.firebaseapp.com',
    storageBucket: 'todoapp-f05fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM6ROxU8Z6g92QLzFIvOFYIz24nae5ITM',
    appId: '1:716646968054:android:eef91134cd0da6667e9ad7',
    messagingSenderId: '716646968054',
    projectId: 'todoapp-f05fe',
    storageBucket: 'todoapp-f05fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuvd8CExay8iZguHZX0LJA9F01nkh4JKM',
    appId: '1:716646968054:ios:94506d37c24812537e9ad7',
    messagingSenderId: '716646968054',
    projectId: 'todoapp-f05fe',
    storageBucket: 'todoapp-f05fe.appspot.com',
    iosClientId: '716646968054-fjl36158ijaoiksem6s6qjcjsar1hcku.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuvd8CExay8iZguHZX0LJA9F01nkh4JKM',
    appId: '1:716646968054:ios:721ab36239fe95f67e9ad7',
    messagingSenderId: '716646968054',
    projectId: 'todoapp-f05fe',
    storageBucket: 'todoapp-f05fe.appspot.com',
    iosClientId: '716646968054-5trehn7ekgo90ok8f603ghkp3h5fjeft.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp.RunnerTests',
  );
}
